service: import-map-deployer

custom:
  bucket: 'mfe-portal-3c8600'

package:
  exclude:
    - 'bin/*'
    - 'examples/**'
    - 'spec/**'
    - '.vscode/**'
    - '*'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: 'arn:aws:s3:::${self:custom.bucket}/*'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  http:
    handler: src/lambda.handler
    timeout: 2
    events:
      - http: ANY /
      - http: ANY /{proxy+}
